services:
  - type: web
    name: flask-finvision
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
    healthCheckPath: / 